#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "fail2ban-web"
name = "Fail2Ban Webinterface"
description.en = "Monitor Fail2Ban and manually ban / release IP's"
description.fr = "Monitorer Fail2Ban et bannir ou dé-bannir des IP's"

version = "1.1~ynh1"

maintainers = ["ewilly"]

[upstream]
license = "AGPL-3.0-or-later"
code = "https://github.com/ewilly/fail2ban-web-interface-php"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/fail2ban-web"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/ewilly/fail2ban-web-interface-php/archive/refs/tags/v1.1.tar.gz"
        sha256 = "de3570fb28a03844a87aad55343465760c0081d379397ac916d73f1a1b05c997"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    main.auth_header = false
    main.show_tile = true
    main.protected= true
    main.allowed = "admins"

    [resources.apt]
    packages = "fail2ban, php8.3-fpm"
