#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_config_remove_phpfpm

ynh_safe_rm "/usr/local/bin/$app"
ynh_safe_rm "/etc/sudoers.d/$app"

#=================================================
# RESTART SYSTEMD SERVICE
#=================================================
ynh_script_progression "Restarting fail2ban service..."

ynh_systemctl --service="fail2ban" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
