#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

ynh_remove_systemd_config

ynh_remove_nginx_config

ynh_remove_fpm_config

ynh_secure_remove --file="/etc/sudoers.d/$app"

#=================================================
# RESTART SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Restarting fail2ban service..." --weight=1

ynh_systemd_action --service_name="fail2ban" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
